import './globals.linaria.global';
import { Inter, Agbalumo } from 'next/font/google';
import NavBar from '~/components/NavBar';
import Providers from '~/components/providers';

const inter = Inter({ subsets: ['latin'] });
// const agbalumo = Agbalumo({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />

          {children}
        </Providers>
      </body>
    </html>
  );
}
